### ISSUE TITLE
脚本失效

### ISSUE THREAD

**Issue by TYZQ** [marioplus/steam-price-converter#3]
f12控制台信息如下
![QQ截图20221221075639](https://user-images.githubusercontent.com/44107135/208789567-3abdc60c-8ce6-40e8-b2b4-87b0c0884475.png)

```
FRegionalPricing.js:133 Error: Could not establish conversion rate between ARS and TRY
    at H.inCurrency (Price.js:37:19)
    at He._getCountryHTML (FRegionalPricing.js:94:41)
    at He.apply (FRegionalPricing.js:62:49)
    at async FeatureManager.js:94:21
    at async Promise.allSettled (/app/1659420/UNCHARTED/index 22)
    at async Function.apply (FeatureManager.js:39:9)
    at async run.constructor.run (Page.js:102:29)
_handleError @ FRegionalPricing.js:133
```

**Comment by marioplus** [comment]
你所提供的报错并不是本脚本的，但我确实发现脚本不能使用了，新开了 #5 ，你看看还有没有问题。

**Comment by TYZQ** [comment]
实测没有问题了，谢谢大佬
